"use client";

import Image from "next/image";
import Link from "next/link";
import { Building2, ChevronDown, Home, LandPlot, MapPin, MessageCircle, Search, Store } from "lucide-react";
import { FormEvent, useState } from "react";

const categories = [["همه", Home], ["آپارتمان", Building2], ["ویلا", Home], ["زمین", LandPlot], ["تجاری", Store]] as const;
const listings = [["ویلای مدرن در محمودآباد", "خرید", "۴۵۰ متر زمین · ۲۸۰ متر بنا", "تماس برای قیمت"], ["آپارتمان نزدیک ساحل", "اجاره", "۱۱۰ متر · دو خواب", "تماس برای قیمت"], ["زمین سرمایه‌گذاری", "خرید", "۳۲۰ متر · سنددار", "تماس برای قیمت"]] as const;

function SelectField({ label, value }: { label: string; value: string }) {
  return <button type="button" className="flex min-h-[72px] w-full items-center justify-between px-5 text-right transition hover:bg-slate-50"><ChevronDown className="shrink-0 text-slate-900" size={18} /><span><span className="block text-xs text-slate-400">{label}</span><span className="mt-1 block text-sm font-extrabold text-[#102847]">{value}</span></span></button>;
}

export default function HomePage() {
  const [activeCategory, setActiveCategory] = useState("همه");
  const [didSearch, setDidSearch] = useState(false);
  const visibleListings = activeCategory === "همه" ? listings : listings.filter(([title]) => title.includes(activeCategory));
  function handleSearch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setDidSearch(true); document.getElementById("listings")?.scrollIntoView({ behavior: "smooth", block: "start" }); }

  return <main className="overflow-hidden bg-white">
    <section className="border-b border-[#d9e9e8] bg-[#f0fbfa]"><div className="mx-auto max-w-7xl px-5 pb-12 pt-20 sm:px-8 sm:pb-14 sm:pt-24">
      <div className="mx-auto max-w-4xl text-center"><h1 className="text-4xl font-black leading-[1.4] tracking-tight text-[#102847] sm:text-5xl">دنبال ملک توی محمودآباد می‌گردی؟<br /><span className="text-[#129b96]">ماهور کنارته.</span></h1><p className="mt-6 text-base leading-8 text-slate-600 sm:text-lg">خرید، فروش، رهن و اجاره با شناخت دقیق منطقه و همراهی مستقیم مشاوران ماهور.</p></div>
      <form onSubmit={handleSearch} className="mt-16 rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_14px_30px_rgba(16,40,71,0.12)]"><div className="grid overflow-hidden rounded-xl sm:grid-cols-[repeat(4,1fr)_120px]"><div className="border-b border-slate-200 sm:border-b-0 sm:border-l"><SelectField label="نوع معامله" value="همه" /></div><div className="border-b border-slate-200 sm:border-b-0 sm:border-l"><SelectField label="نوع ملک" value="همه" /></div><div className="border-b border-slate-200 sm:border-b-0 sm:border-l"><SelectField label="محدوده قیمت" value="همه" /></div><div className="border-b border-slate-200 sm:border-b-0"><SelectField label="موقعیت" value="همه مناطق محمودآباد" /></div><button type="submit" className="m-1 flex min-h-[64px] items-center justify-center gap-2 rounded-lg bg-[#159e9b] px-4 font-extrabold text-white transition hover:bg-[#0d817e]"><Search size={20} />جستجو</button></div></form>
      <div className="mt-12 flex flex-wrap justify-center gap-3">{categories.map(([label, Icon]) => <button key={label} onClick={() => { setActiveCategory(label); setDidSearch(false); }} className={`inline-flex items-center gap-2 rounded-full border px-5 py-3 text-sm font-bold transition ${activeCategory === label ? "border-[#159e9b] bg-[#e8f7f6] text-[#087e7b]" : "border-slate-200 bg-white text-slate-600 hover:border-[#159e9b]"}`}><Icon size={17} strokeWidth={1.8} />{label}</button>)}</div>
    </div></section>

    <section id="listings" className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="text-right"><h2 className="text-3xl font-black text-[#102847]">جدیدترین آگهی‌ها</h2><p className="mt-3 text-slate-500">فایل‌های منتخب برای خرید و اجاره در محمودآباد</p></div><Link href="/register" className="inline-flex items-center gap-2 self-start font-bold text-[#129b96] transition hover:text-[#102847]">ثبت آگهی رایگان <span aria-hidden="true">←</span></Link></div>{didSearch && <p className="mt-6 rounded-xl bg-[#e8f7f6] px-4 py-3 text-sm font-bold text-[#087e7b]">نتایج پیشنهادی بر اساس جست‌وجوی شما نمایش داده شد.</p>}<div className="mt-9 grid gap-6 md:grid-cols-3">{visibleListings.length ? visibleListings.map(([title, deal, details, price], index) => <article key={title} className="overflow-hidden rounded-2xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-[0_16px_28px_rgba(16,40,71,0.12)]"><div className="relative h-48 bg-[#eaf4f3]"><Image src="/images/mahoor-hero-v1.png" alt={title} fill className={`object-cover ${index === 1 ? "object-center" : "object-left"}`} sizes="(max-width: 768px) 100vw, 33vw" /><span className="absolute right-4 top-4 rounded-full bg-white px-3 py-1.5 text-xs font-extrabold text-[#159e9b] shadow">{deal}</span></div><div className="p-5 text-right"><h3 className="text-lg font-extrabold text-[#102847]">{title}</h3><p className="mt-2 flex items-center justify-end gap-1 text-sm text-slate-500"><MapPin size={15} />محمودآباد، مازندران</p><p className="mt-4 border-t border-slate-100 pt-4 text-sm text-slate-600">{details}</p><p className="mt-3 font-extrabold text-[#129b96]">{price}</p></div></article>) : <div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-500 md:col-span-3">برای این دسته‌بندی آگهی نمونه‌ای نداریم؛ همهٔ آگهی‌ها را ببینید.</div>}</div></section>

    <section className="bg-[#102847] px-5 py-16 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-9 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div className="text-right"><h2 className="text-3xl font-black">دفتر ماهور، نزدیک شما</h2><p className="mt-4 leading-8 text-slate-300">محمودآباد، خیابان امام، بعد از نسیم ۶۹/۱. برای مشاوره و بازدید ملک با ما در تماس باشید.</p><div className="mt-7 flex flex-wrap justify-end gap-3"><a href="tel:01144735333" className="rounded-xl border border-white/20 px-5 py-3 font-bold transition hover:bg-white/10">۰۱۱ ۴۴۷۳ ۵۳۳۳</a><a href="https://wa.me/989120996426" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-[#25D366] px-5 py-3 font-extrabold text-white transition hover:bg-[#1ebd5a]"><MessageCircle size={19} />واتساپ</a></div></div><div className="overflow-hidden rounded-2xl border border-white/15 bg-white"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3232.0!2d52.2607!3d36.6333!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8eb760f2e84c87%3A0x0!2z2YXYrdmF2YjYr9in2KjYp9ivINmF2KfYmdmI2LMg2LnYsiDZhdix2YPYsiDZhdi52YPZhdin2KvYp9ioINmF2K_YrdmF2YjYr9in2KjYp9iv!5e0!3m2!1sfa!2sir!4v1700000000000!5m2!1sfa!2sir" width="100%" height="290" className="border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" title="موقعیت دفتر املاک ماهور" /></div></div></section>

    <section className="bg-[#f0fbfa] px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[0.9fr_1.1fr] md:items-center"><div className="overflow-hidden rounded-2xl border border-[#cfe7e5] bg-white"><video className="aspect-video w-full object-cover" autoPlay loop muted playsInline preload="metadata" poster="/images/mahoor-logo-v1.png" aria-label="ویدیوی معرفی برند ماهور"><source src="/videos/mahoor-brand-v1.mp4" type="video/mp4" /></video></div><div className="text-right"><h2 className="text-3xl font-black text-[#102847]">اعتماد، در هر نگاه</h2><p className="mt-4 leading-8 text-slate-600">ماهور با شناخت منطقه و تجربهٔ واقعی در بازار، برای انتخاب بهتر کنار شماست.</p><Link href="/about" className="mt-6 inline-flex items-center gap-2 font-bold text-[#129b96]">بیشتر درباره ماهور <span aria-hidden="true">←</span></Link></div></div></section>
  </main>;
}
